#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#3EC669'
    background = '#29315A'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#43CCEA'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'python'
    style = 'diamond'
    foreground = '#E4F34A'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'go'
    style = 'diamond'
    foreground = '#7FD5EA'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'node'
    style = 'diamond'
    foreground = '#42E66C'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'ruby'
    style = 'diamond'
    foreground = '#E64747'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'java'
    style = 'diamond'
    foreground = '#E64747'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'julia'
    style = 'diamond'
    foreground = '#9B6BDF'
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'php'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#4063D8'
    leading_diamond = ' '
    trailing_diamond = ''
    template = ' {{ .Full }} '

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'battery'
    style = 'diamond'
    foreground = '#9B6BDF'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']
    background = '#29315A'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}'

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = '⇡ '
      discharging_icon = '⇣ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#AEA4BF'
    background = '#29315A'
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150.0

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    foreground = '#E64747'
    background = '#29315A'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .UserName }} ❯'
